### ISSUE TITLE
Ignore namespaces when dealing with ClusterRole or ClusterRoleBindings

### ISSUE THREAD

**Issue by Bhashit** [kbst/terraform-provider-kustomize#26]
While installing Istio with CNI, I had a manifest generated using istioctl. The manifest incorrectly creates a ClusterRoleBinding that specifies a namespace:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-cni-repair-rolebinding
  namespace: kube-system
  labels:
    k8s-app: istio-cni-repair
subjects:
- kind: ServiceAccount
  name: istio-cni
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-cni-repair-role

```

This refers to another `ClusterRole`

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-cni-repair-role
  labels:
    app: istio-cni
    release: istio
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete", "patch", "update" ]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "delete", "patch", "update", "create" ]
```

Because the `ClusterRoleBinding` specifies a namespace, it looks like this provider is trying to look for a resource in that namespace. It fails with the following error.

```
module.cluster-services.kustomization_resource.current["rbac.authorization.k8s.io_v1_ClusterRoleBinding|kube-system|istio-cni-repair-rolebinding"]: Creating...
 Error: ResourceCreate: creating 'rbac.authorization.k8s.io/v1, Resource=clusterrolebindings' failed: the server could not find the requested resource
```

This may be an easy fix, and I'll attempt to send a PR once I have fixed this issue from happening in my CI pipeline.
